name: Dev-Builds
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: openjdk:15-jdk
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1.0.3
      - run: chmod +x ./gradlew
      - run: ./gradlew setup installerJar
        env:
          STABLE_BUILD: 0
    #   - uses: actions/upload-artifact@v2.2.2
    #     with:
    #       name: Builds
    #       path: build/distributions/*server.*
